language: zh-Hans

theme:
  switch: true
  default: style-dark

  
favicon:
  logo: https://counter.imalun.com/www.acerkaio.top?theme=rule34
  icon16: https://cdn.luogu.com.cn/upload/usericon/514850.png
  icon32: https://cdn.luogu.com.cn/upload/usericon/514850.png
  apple_touch_icon: apple-touch-icon.png
  webmanifest: /site.webmanifest
  visibilitychange: true
  hidden: failure.ico
  show_text: (/≧▽≦/)咦！又好了！
  hide_text: 加载失败...
  
user:
  name: ACerKa1o
  first_name: 
  last_name: 
  email: what667172@163.com
  domain: https://blog.acerkaio.top/
  avatar: https://cdn.luogu.com.cn/upload/usericon/514850.png
  describe: 网站简介。
  rule_text: 暂不接受个人博客以外的友链申请，确保您的网站内容积极向上，文章至少30篇，原创70%以上，部署HTTPS。

sidebar:
  social: # 社交地址
    - name: github
      icon: fab fa-github
      url: https://github.com/Acerkaio
    - name: steam
      icon: fab fa-steam
      url: https://steamcommunity.com/id/Acerkaio/
    - name: 知乎
      icon: fab fa-zhihu
      url: https://www.zhihu.com/people/acerkaio
    - name: 洛谷
      icon: fas fa-code
      url: https://www.luogu.com/user/514850
  typed_text_prefix: I`m
  typed_text: ["an ordinary person."]
  info:
    - key: 地址
      val: CHINA
    - key: 年龄
      val: 15
banner:
  index:
    type: video
    bgurl: https://cdn.jsdelivr.net/gh/Acerkaio/ImageHost/test/%E6%99%9A%E4%B8%8A.mp4
    banner_title: 花径不曾缘客扫，<br>蓬门今始为君开。
    banner_text: Hola, Acerkaio here!
	danmu: 
		enable: true
		avatar: true
		delayRange: 5000
		speed: 80
footer:
  powered:
    enable: true
  beian:
    enable: false
    icp:
  copyright_year: 2022
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 08/30/2022 00:00:00
  custom_text: HOLA!
lazyload:
  enable: true
notice_outdate:
  enable: true
  style: flat
  limit_day: 365
  position: top
rightside:
  readmode: true
  aside: true
  
top_bars:
  - title: menu.home
    url: /
  - title: menu.archives
    url: /archives/
  - title: menu.links
    url: /links/
  - title: menu.about
    url: /about/
  - title: album
    url: /album/
    

links:
  - name: hellolin
    url: //www.hellolin.top/
    image: //cdn.luogu.com.cn/upload/usericon/751017.png
    desc: 现役 OIer / 前端技术爱好者
  - name: Tibrella
    url: //tibrella.space/
    image: //tibrella.space/img/avatar.webp
    desc: Wash away the anger. 
  - name: 白云苍狗
    url: //www.imalun.com/
    image: //www.imalun.com/images/avatar.jpg
    desc: 醒，亦在人间；梦，亦在人间

about:
  insert: before # 插入规则 before（插入在内容前） | after（插入在内容后） | none（不插入）
  title: 花径不曾缘客扫，蓬门今始为君开。
  introduction: <strong>这是个神秘的地方：是个人的日志，是中二的语集，是成长的见证？至少我希望总能在互联网的波涛中绽放光彩。</strong><br><br> <span>——Acerkaio/Shawn</div>
  blog: <h4>发电日常罢了</h4><br>程序：Hexo<br>主题：Hexo-theme-async<br>托管：Vercel
  privacy: # 隐私权说明
